"use client";
import React,{useState} from 'react';
import { useFirestore,useUser,useDoc,useMemoFirebase,useCollection } from '@/firebase';
import { collection,query,where,doc,orderBy } from 'firebase/firestore';
import { reviewCourse } from '@/lib/course-service';
import { Card } from '@/components/ui/card'; import { Button } from '@/components/ui/button'; import { Badge } from '@/components/ui/badge'; import { Textarea } from '@/components/ui/textarea'; import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter } from '@/components/ui/dialog'; import { Avatar,AvatarFallback,AvatarImage } from '@/components/ui/avatar'; import { CheckCircle2,XCircle,Clock,Eye,Lock } from 'lucide-react'; import { useToast } from '@/hooks/use-toast';
export default function CourseReviews(){const db=useFirestore();const {user}=useUser();const {toast}=useToast();const [selected,setSelected]=useState<any>(null);const [reason,setReason]=useState('');
 const profileRef=useMemoFirebase(()=>user?doc(db,'users',user.uid):null,[db,user]);const {data:profile}=useDoc(profileRef);const isAdmin=!!(profile?.isAdmin||user?.email==='mohamed76y@gmail.com'||user?.email==='mohamjedminijd2006@gmail.com');
 const q=useMemoFirebase(()=>isAdmin?query(collection(db,'courses'),where('status','==','pending')):null,[db,isAdmin]);const {data:courses,isLoading}=useCollection(q);
 const act=async(dec:'approved'|'rejected')=>{if(!selected)return;try{await reviewCourse(db,selected.id,user!.uid,profile?.name||user?.displayName||'Admin',dec,reason);toast({title:dec==='approved'?'تم اعتماد الكورس':'تم رفض الكورس',description:dec==='approved'?'أصبح منشورًا للطلاب.':'تم حفظ سبب الرفض وإبلاغ صاحب الكورس.'});setSelected(null);setReason('')}catch(e:any){toast({variant:'destructive',title:'تعذر تنفيذ القرار',description:e.message})}};
 if(!isAdmin)return <div className="p-20 text-center font-black">لا تملك صلاحية مراجعة الكورسات.</div>;
 return <div className="p-6 md:p-10 space-y-8" dir="rtl"><div className="border-r-8 border-primary pr-5"><h1 className="text-4xl font-black">مراجعة الكورسات</h1><p className="text-muted-foreground">أي كورس جديد يصل هنا بحالة قيد المراجعة ولا يظهر للطلاب.</p></div>{isLoading?<div className="py-20 text-center">جاري التحميل...</div>:!courses?.length?<div className="py-24 text-center text-zinc-400 font-black">لا توجد كورسات بانتظار المراجعة.</div>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{courses.map((c:any)=><Card key={c.id} className="rounded-3xl overflow-hidden"><div className="aspect-video bg-zinc-100">{c.coverUrl&&<img src={c.coverUrl} className="w-full h-full object-cover"/>}</div><div className="p-5 space-y-3"><Badge className="bg-amber-100 text-amber-700"><Clock className="w-3 h-3 ml-1"/>قيد المراجعة</Badge><h2 className="font-black text-xl">{c.title}</h2><p className="text-sm text-zinc-500 line-clamp-3">{c.description}</p><div className="flex items-center gap-3"><Avatar><AvatarImage src={c.instructorAvatar}/><AvatarFallback>{String(c.instructorName||'م').slice(0,1)}</AvatarFallback></Avatar><div className="text-sm font-bold">{c.instructorName}<div className="text-xs text-zinc-400">{c.price} ج.م {c.promotionalPrice?`• ترويجي ${c.promotionalPrice} ج.م`:''}</div></div></div><Button className="w-full rounded-xl" onClick={()=>setSelected(c)}><Eye className="w-4 h-4 ml-2"/> فتح المراجعة</Button></div></Card>)}</div>}
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto rounded-3xl" dir="rtl"><DialogHeader><DialogTitle className="text-2xl font-black">مراجعة: {selected?.title}</DialogTitle></DialogHeader><div className="space-y-5"><img src={selected?.coverUrl} className="w-full max-h-72 object-cover rounded-2xl"/><div className="p-4 rounded-2xl bg-zinc-50"><b>الوصف</b><p className="mt-2 leading-7">{selected?.description}</p></div><div className="grid md:grid-cols-3 gap-3"><div className="p-4 rounded-xl border"><b>السعر</b><p>{selected?.price} ج.م</p></div><div className="p-4 rounded-xl border"><b>السعر الترويجي</b><p>{selected?.promotionalPrice||'لا يوجد'}</p></div><div className="p-4 rounded-xl border"><b>المفهم</b><p>{selected?.instructorName}</p></div></div><div><b>سبب الرفض (إجباري عند الرفض)</b><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="اكتب سببًا واضحًا ليستطيع صاحب الكورس معالجة الملاحظات..." className="mt-2"/></div></div><DialogFooter><Button variant="destructive" onClick={()=>act('rejected')} disabled={!reason.trim()}><XCircle className="ml-2"/>رفض وحفظ السبب</Button><Button onClick={()=>act('approved')}><CheckCircle2 className="ml-2"/>قبول ونشر</Button></DialogFooter></DialogContent></Dialog>
 </div>}
