"use client";
import React, { useEffect, useRef, useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Upload, Trash2, ArrowUp, ArrowDown, Loader2, Film, ImageIcon } from 'lucide-react';
import { Course, CourseLesson } from '@/lib/types';
import { uploadCourseFile, saveCourseWithLessons } from '@/lib/course-service';
import { useFirebase, useFirestore } from '@/firebase';
import { doc, setDoc } from 'firebase/firestore';
import { serverTimestamp } from 'firebase/firestore';
import { useToast } from '@/hooks/use-toast';

interface Props { open:boolean; onOpenChange:(v:boolean)=>void; courseToEdit?:Course|null; instructorId:string; instructorName:string; instructorAvatar?:string; onSaved?:()=>void; }
export function CourseEditorDialog({open,onOpenChange,courseToEdit,instructorId,instructorName,instructorAvatar,onSaved}:Props){
 const {storage}=useFirebase(); const db=useFirestore(); const {toast}=useToast();
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[price,setPrice]=useState(0),[promo,setPromo]=useState(''),[category,setCategory]=useState('البرمجة والتقنية'),[features,setFeatures]=useState('');
 const [draftId,setDraftId]=useState(courseToEdit?.id || '');
 const [cover,setCover]=useState<any>(null),[lessons,setLessons]=useState<CourseLesson[]>([]),[uploading,setUploading]=useState(false),[saving,setSaving]=useState(false);
 const coverRef=useRef<HTMLInputElement>(null); const videoRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{ if(!open)return; setDraftId(courseToEdit?.id || `course-${Date.now()}-${Math.random().toString(36).slice(2,7)}`); setTitle(courseToEdit?.title||'');setDescription(courseToEdit?.description||'');setPrice(courseToEdit?.price||0);setPromo(courseToEdit?.promotionalPrice?.toString()||'');setCategory(courseToEdit?.category||'البرمجة والتقنية');setFeatures((courseToEdit?.features||[]).join('\n'));setCover(courseToEdit?.coverStoragePath?{...courseToEdit,downloadUrl:courseToEdit.coverUrl}:null);setLessons(courseToEdit?.lessons||[]);},[open,courseToEdit]);
 const ensureDraft=async()=>{await setDoc(doc(db,'courses',draftId),{id:draftId,instructorId,instructorName,instructorAvatar,status:'pending',isPublished:false,createdAt:serverTimestamp()},{merge:true});};
 const addCover=async(file:File)=>{try{setUploading(true);await ensureDraft();const r=await uploadCourseFile(storage,file,draftId,'cover');setCover(r);toast({title:'تم رفع صورة الكورس'});}catch(e:any){toast({variant:'destructive',title:'تعذر رفع الصورة',description:e.message});}finally{setUploading(false)}};
 const addVideo=async(file:File)=>{const number=lessons.length+1;if(number>110){toast({variant:'destructive',title:'تم الوصول للحد الأقصى',description:'يمكن إضافة 110 درسًا فقط لكل كورس.'});return;}try{setUploading(true);await ensureDraft();const r=await uploadCourseFile(storage,file,draftId,'lesson',number);const duration=await new Promise<number>(resolve=>{const v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{URL.revokeObjectURL(v.src);resolve(Math.round(v.duration));};v.src=URL.createObjectURL(file);});setLessons(prev=>[...prev,{id:`lesson-${Date.now()}`,title:file.name.replace(/\.[^/.]+$/,'').replace(/[-_]+/g,' '),storagePath:r.storagePath,videoUrl:r.downloadUrl,videoFileName:r.fileName,videoFileSize:String(r.fileSize),durationMinutes:Math.ceil(duration/60),durationSeconds:duration,order:number,lessonNumber:number,isFreePreview:number===1}]);toast({title:`تم رفع الدرس ${String(number).padStart(2,'0')}`});}catch(e:any){toast({variant:'destructive',title:'تعذر رفع الفيديو',description:e.message});}finally{setUploading(false)}};
 const move=(i:number,d:number)=>{const a=[...lessons],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];setLessons(a.map((l,k)=>({...l,order:k+1,lessonNumber:k+1,isFreePreview:k===0}))) };
 const remove=(i:number)=>setLessons(lessons.filter((_,k)=>k!==i).map((l,k)=>({...l,order:k+1,lessonNumber:k+1,isFreePreview:k===0})));
 const save=async()=>{if(lessons.length>110||lessons.some((l,i)=>l.lessonNumber!==i+1||l.order!==i+1||!l.title.trim())){toast({variant:'destructive',title:'ترتيب الدروس غير صحيح',description:'يجب أن تكون عناوين الدروس موجودة ومرتبة من 1 إلى 110 بدون أرقام مفقودة.'});return;}if(!title.trim()||!description.trim()||lessons.length<1||!cover?.storagePath){toast({variant:'destructive',title:'بيانات ناقصة',description:'أكمل الاسم والوصف والصورة ودرسًا واحدًا على الأقل.'});return;} try{setSaving(true);const id=draftId;let finalCover=cover;if(!finalCover.storagePath) throw new Error('صورة الغلاف غير مرفوعة');const course:Course={id,title:title.trim(),description:description.trim(),coverUrl:finalCover.downloadUrl||finalCover.coverUrl,coverStoragePath:finalCover.storagePath,coverFileName:finalCover.fileName,price:Number(price)||0,promotionalPrice:promo?Number(promo):null,features:features.split('\n').map(x=>x.trim()).filter(Boolean),lessons,instructorId,instructorName,instructorAvatar,status:courseToEdit?.status==='published'?'published':'pending',isPublished:courseToEdit?.status==='published',category,createdAt:courseToEdit?.createdAt||new Date().toISOString(),submittedAt:courseToEdit?.submittedAt||new Date().toISOString(),totalEnrollments:courseToEdit?.totalEnrollments||0,rating:courseToEdit?.rating||5};await saveCourseWithLessons(db,course,lessons,courseToEdit?.lessons.map(l=>l.id)||[]);toast({title:'تم إرسال الكورس للمراجعة',description:'حالة الكورس الآن: قيد المراجعة، ولن يظهر للطلاب قبل موافقة الأدمن.'});onOpenChange(false);onSaved?.();}catch(e:any){toast({variant:'destructive',title:'فشل الحفظ',description:e.message});}finally{setSaving(false)}};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-4xl max-h-[92vh] overflow-y-auto rounded-[2rem]" dir="rtl"><DialogHeader className="text-right"><DialogTitle className="text-2xl font-black">{courseToEdit?'تعديل الكورس':'إنشاء كورس جديد'}</DialogTitle><DialogDescription>كل كورس جديد يُرسل تلقائيًا إلى حالة «قيد المراجعة».</DialogDescription></DialogHeader>
 <div className="space-y-6 py-4">
  <div className="p-4 rounded-2xl bg-amber-50 border border-amber-200"><b>الحالة:</b> {courseToEdit?.status==='published'?'منشور':'قيد المراجعة'} — لا يمكن نشر الكورس من المُفهم مباشرة.</div>
  <div className="grid md:grid-cols-2 gap-4"><div><Label>اسم الكورس *</Label><Input value={title} onChange={e=>setTitle(e.target.value)} /></div><div><Label>السعر *</Label><Input type="number" value={price} onChange={e=>setPrice(Number(e.target.value))}/></div><div><Label>السعر الترويجي</Label><Input type="number" value={promo} onChange={e=>setPromo(e.target.value)} placeholder="اختياري"/></div><div><Label>التصنيف</Label><Input value={category} onChange={e=>setCategory(e.target.value)}/></div></div>
  <div><Label>الوصف *</Label><Textarea value={description} onChange={e=>setDescription(e.target.value)} rows={5}/></div>
  <div><Label>المميزات والتفاصيل — كل ميزة في سطر</Label><Textarea value={features} onChange={e=>setFeatures(e.target.value)} rows={4}/></div>
  <div className="p-5 border-2 border-dashed rounded-2xl"><div className="flex justify-between items-center mb-3"><Label className="font-black"><ImageIcon className="inline w-4 h-4 ml-1"/> صورة الكورس</Label><Button type="button" variant="outline" onClick={()=>coverRef.current?.click()}><Upload className="w-4 h-4 ml-2"/> رفع</Button></div><input ref={coverRef} type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&addCover(e.target.files[0])}/>{cover?.downloadUrl||cover?.coverUrl?<img src={cover.downloadUrl||cover.coverUrl} className="w-full max-h-64 object-cover rounded-xl"/>:<p className="text-sm text-muted-foreground">لم يتم رفع صورة بعد.</p>}</div>
  <div className="p-5 border rounded-2xl"><div className="flex justify-between items-center mb-4"><div><h3 className="font-black">الدروس والفيديوهات</h3><p className="text-xs text-muted-foreground">الدرس الأول معاينة مجانية، والدرس 02 وما بعده مقفول حتى الشراء.</p></div><Button type="button" onClick={()=>videoRef.current?.click()} disabled={uploading}><Film className="w-4 h-4 ml-2"/> رفع فيديو</Button></div><input ref={videoRef} type="file" accept="video/*" hidden onChange={e=>e.target.files?.[0]&&addVideo(e.target.files[0])}/>
   <div className="space-y-2">{lessons.map((l,i)=><div key={l.id} className="p-3 rounded-xl bg-zinc-50 border space-y-2"><div className="flex items-center gap-3"><Badge className="shrink-0">{i+1}-</Badge><Input value={l.title} required maxLength={160} onChange={e=>setLessons(prev=>prev.map((x,k)=>k===i?{...x,title:e.target.value}:x))} className="flex-1 font-bold" placeholder={`عنوان الدرس ${i+1}`} /><div className="flex items-center gap-1"><Button size="icon" variant="ghost" onClick={()=>move(i,-1)} disabled={i===0}><ArrowUp/></Button><Button size="icon" variant="ghost" onClick={()=>move(i,1)} disabled={i===lessons.length-1}><ArrowDown/></Button><Button size="icon" variant="ghost" className="text-red-500" onClick={()=>remove(i)}><Trash2/></Button></div></div><div className="text-xs text-muted-foreground pr-1">{l.isFreePreview?'معاينة مجانية':'مقفول حتى الشراء'} • {Math.round((l.durationSeconds||l.durationMinutes*60)/60)} دقيقة • {l.videoFileName}</div><div className="text-[11px] text-zinc-500 font-mono break-all">رابط الدرس: /courses/course-{i+1}-{draftId.replace(/^course-/,'')}</div></div>)}{!lessons.length&&<p className="text-center py-8 text-muted-foreground">ارفع أول فيديو لإضافة الدرس 01.</p>}</div>
  </div>
 </div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>إلغاء</Button><Button onClick={save} disabled={saving||uploading}>{saving?<Loader2 className="animate-spin ml-2"/>:null} إرسال للمراجعة</Button></DialogFooter></DialogContent></Dialog>
}
