"use client";
import React,{useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation'; import Link from 'next/link';
import {Lock,Play,ShoppingCart,Clock,CheckCircle2,ArrowRight,User} from 'lucide-react';
import {useFirebase,useFirestore,useDoc,useMemoFirebase} from '@/firebase'; import {doc} from 'firebase/firestore';
import {getCourseFromFirestore,hasPurchased,purchaseCourse} from '@/lib/course-service'; import type {Course,CourseLesson} from '@/lib/types';
import {Button} from '@/components/ui/button'; import {Badge} from '@/components/ui/badge'; import {Avatar,AvatarFallback,AvatarImage} from '@/components/ui/avatar'; import {Card} from '@/components/ui/card'; import {useToast} from '@/hooks/use-toast';
export default function CourseDetailPage(){const {id}=useParams();const routeId=Array.isArray(id)?id[0]:String(id||'');const lessonMatch=routeId.match(/^course-(\d+)-(.+)$/);const routeLessonNumber=lessonMatch?Number(lessonMatch[1]):null;const courseId=lessonMatch?`course-${lessonMatch[2]}`:routeId;const router=useRouter();const {user}=useFirebase();const db=useFirestore();const {toast}=useToast();const [course,setCourse]=useState<Course|null>(null);const [bought,setBought]=useState(false);const [selected,setSelected]=useState(0);const [loading,setLoading]=useState(true);const profileRef=useMemoFirebase(()=>user?doc(db,'users',user.uid):null,[db,user]);const {data:profile}=useDoc(profileRef);
 useEffect(()=>{(async()=>{if(!courseId)return;setLoading(true);try{const c=await getCourseFromFirestore(db,courseId);if(c&&c.status==='published'){setCourse(c);if(user)setBought(await hasPurchased(db,user.uid,c.id));}else setCourse(null)}finally{setLoading(false)}})()},[db,courseId,user]);useEffect(()=>{if(!course||!routeLessonNumber)return;const index=(course.lessons||[]).findIndex(l=>l.lessonNumber===routeLessonNumber);if(index>=0)setSelected(index)},[course,routeLessonNumber]);
 if(loading)return <div className="p-20 text-center">جاري التحميل...</div>; if(!course)return <div className="p-20 text-center font-black">الكورس غير موجود أو غير منشور.</div>;
 const lessons=course.lessons||[];const lesson=lessons[selected];const locked=!bought&&selected>0;const price=course.promotionalPrice||course.price;const buy=async()=>{if(!user){router.push('/login');return}try{await purchaseCourse(db,user.uid,course);setBought(true);toast({title:'تم الشراء بنجاح',description:'تم فتح جميع الدروس.'})}catch(e:any){toast({variant:'destructive',title:'تعذر الشراء',description:e.message})}};
 return <div className="min-h-screen bg-zinc-50 py-8 px-4 md:px-8" dir="rtl"><div className="max-w-6xl mx-auto space-y-7"><Button asChild variant="ghost"><Link href="/courses"><ArrowRight className="ml-2"/>العودة للكورسات</Link></Button><Card className="overflow-hidden rounded-[2rem]"><div className="grid lg:grid-cols-3"><div className="lg:col-span-2"><img src={course.coverUrl} className="w-full aspect-video object-cover"/><div className="p-7 space-y-5"><div className="flex gap-2"><Badge>{course.category}</Badge>{bought&&<Badge className="bg-emerald-600">تم الشراء</Badge>}</div><h1 className="text-3xl font-black">{course.title}</h1><p className="text-zinc-600 leading-8">{course.description}</p><div className="flex items-center gap-3"><Avatar><AvatarImage src={course.instructorAvatar}/><AvatarFallback><User/></AvatarFallback></Avatar><div><b>{course.instructorName}</b><div className="text-xs text-zinc-500">المُفهم</div></div></div>{lesson&&routeLessonNumber!==null&&routeLessonNumber!==1&&<div className="bg-black rounded-2xl overflow-hidden aspect-video relative">{locked?<div className="absolute inset-0 flex flex-col items-center justify-center text-white gap-3"><Lock className="w-12 h-12"/><b>هذا الدرس متاح بعد شراء الكورس</b><Button onClick={buy} className="rounded-xl"><ShoppingCart className="ml-2"/>شراء الكورس</Button></div>:<video src={lesson.videoUrl||''} controls controlsList="nodownload" className="w-full h-full object-contain"/>}</div>}</div></div><aside className="p-7 border-r bg-white space-y-5"><div className="text-center"><div className="text-sm text-zinc-500">السعر</div><div className="text-4xl font-black text-primary">{price} ج.م</div>{course.promotionalPrice&&<div className="text-sm line-through text-zinc-400">{course.price} ج.م</div>}</div>{!bought&&<Button onClick={buy} className="w-full h-14 rounded-2xl text-lg font-black"><ShoppingCart className="ml-2"/>شراء الكورس</Button>}<div><h3 className="font-black mb-3">دروس الكورس</h3><div className="space-y-2">{lessons.map((l:CourseLesson,i:number)=><Link key={l.id} href={`/courses/course-${l.lessonNumber}-${course.id.replace(/^course-/,'')}`} className={`w-full text-right p-3 rounded-xl border flex items-center gap-3 ${selected===i?'border-primary bg-primary/5':''}`}><span className="font-mono font-black">{String(l.lessonNumber||i+1).padStart(2,'0')}</span><span className="flex-1 font-bold text-sm">{l.title}</span>{i===0?<Play className="w-4 h-4 text-emerald-600"/>:<Lock className="w-4 h-4 text-zinc-400"/>}</Link>)}</div></div><div className="text-xs text-zinc-500 font-bold"><Clock className="inline w-3 h-3 ml-1"/> الدرس 01 معاينة مجانية — 02+ للمشتري فقط</div></aside></div></Card></div></div>
}
